services:

  redis:
    image: redis:alpine
    ports:
      - "5379:6379"

  seq:
    image: datalust/seq:latest
    ports:
      - "5340:80"
      
  zipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "5411:9411"
    
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04
    container_name: sqldata
    user: root
    environment:
      - SA_PASSWORD
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "5455:1433"
    volumes:
      - template-sqldata:/var/opt/mssql/data/
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s


  bsol-api:
    image: ${DOCKER_REGISTRY:-bsol}/bsol.api:${TAG:-latest}
    container_name: bsol-api
    build:
      context: .
      dockerfile: src/TrackFinance.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ConnectionStrings__SqlServerConnection=${BANCOSOL_DB_CONNECTION}
      - USECACHE =${USECACHE}
    ports:
      - "5101:80"
      - "50002:50001"

  bsol-api-dapr:
    image: daprio/dapr:1.10.0
    command: ["./daprd",
      "-app-id", "bsol-api",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/bsol-config.yaml"
      ]    
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
    network_mode: "service:bsol-api"
    depends_on:
      - bsol-api

volumes:
  template-sqldata:
